import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { MainNavbar } from "@/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col space-y-20">
        <MainNavbar></MainNavbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
