import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { MainNavbar } from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "next-themes";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "IdeaVault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col space-y-10 bg-background text-foreground">
        <ThemeProvider>
          <MainNavbar></MainNavbar>
        <main className="grow">{children}</main>
        <Footer></Footer>
        <Toaster />
        </ThemeProvider>
        </body>
    </html>
  );
}
